export const SportData = [
    {
        createdDate: "2024-08-10T08:15:30.000Z",
        title: "축구 월드컵 예선, 최고의 경기 분석",
        content: "이번 월드컵 예선전에서는 놀라운 반전이 일어난 경기들이 많았습니다. 특히 X팀과 Y팀의 경기는 팬들의 큰 관심을 끌었습니다.",
        postState: "완료",
        sport: "축구",
        viewCount: 2000,
        likeCount: 180,
        commentCount: 65,
        tag: ["축구", "월드컵", "예선"],
        image: "images/football_match_analysis.jpg"
    },
    {
        createdDate: "2024-04-12T14:22:45.000Z",
        title: "러닝에 적합한 러닝화 선택법",
        content: "러닝화를 고를 때는 자신의 발 모양과 주행 스타일에 맞는 신발을 선택하는 것이 중요합니다. 전문가가 추천하는 몇 가지 제품을 소개합니다.",
        postState: "완료",
        sport: "러닝",
        viewCount: 1200,
        likeCount: 130,
        commentCount: 40,
        tag: ["러닝", "운동화", "추천"],
        image: "images/running_shoes_expert.jpg"
    },
    {
        createdDate: "2024-01-13T09:10:00.000Z",
        title: "2024 야구 시즌, 우승팀은 누구일까?",
        content: "올해 야구 시즌이 시작되었으며, 각 팀은 강력한 선수들과 함께 우승을 노리고 있습니다. 전문가들이 예측하는 올해의 우승팀을 확인해보세요.",
        postState: "예측",
        sport: "야구",
        viewCount: 2500,
        likeCount: 210,
        commentCount: 75,
        tag: ["야구", "시즌", "우승예측"],
        image: "images/baseball_team_prediction.jpg"
    },
    {
        createdDate: "2024-11-19T18:45:30.000Z",
        title: "배드민턴을 잘 치려면 꼭 알아야 할 기본 기술",
        content: "배드민턴은 빠른 반응 속도와 정확한 기술이 중요한 스포츠입니다. 이 포스트에서는 배드민턴의 기본 기술과 훈련법에 대해 다룹니다.",
        postState: "완료",
        sport: "배드민턴",
        viewCount: 900,
        likeCount: 95,
        commentCount: 35,
        tag: ["배드민턴", "기술", "훈련"],
        image: "images/badminton_skills.jpg"
    },
    {
        createdDate: "2024-09-11T06:30:15.000Z",
        title: "수영에서 중요한 4가지 기술",
        content: "수영을 잘 하기 위해서는 체력과 함께 중요한 기술들이 있습니다. 이 글에서는 각 수영 스타일에 필요한 기술들을 설명합니다.",
        postState: "완료",
        sport: "수영",
        viewCount: 1800,
        likeCount: 160,
        commentCount: 55,
        tag: ["수영", "기술", "훈련"],
        image: "images/swimming_techniques.jpg"
    },
    {
        createdDate: "2024-09-08T22:50:10.000Z",
        title: "마라톤 대회 준비, 훈련 계획 세우기",
        content: "마라톤 대회를 준비하는 데 중요한 것은 체력 관리와 훈련 계획입니다. 효과적인 훈련 방법을 소개하고, 대회 준비 전략을 세워봅시다.",
        postState: "진행중",
        sport: "마라톤",
        viewCount: 1100,
        likeCount: 120,
        commentCount: 50,
        tag: ["마라톤", "훈련", "준비"],
        image: "images/marathon_training_plan.jpg"
    },
    {
        createdDate: "2024-09-15T07:40:05.000Z",
        title: "농구에서 중요한 기본기 훈련법",
        content: "농구는 기본기가 중요한 스포츠입니다. 드리블, 패스, 슈팅 등 기본기를 다지는 훈련법에 대해 알아보겠습니다.",
        postState: "완료",
        sport: "농구",
        viewCount: 1400,
        likeCount: 135,
        commentCount: 60,
        tag: ["농구", "기본기", "훈련"],
        image: "images/basketball_fundamentals.jpg"
    },
    {
        createdDate: "2024-09-09T16:15:55.000Z",
        title: "초보자를 위한 클라이밍 안전 수칙",
        content: "클라이밍을 시작하는 초보자들이 알아야 할 안전 수칙을 정리했습니다. 안전한 클라이밍을 위해 반드시 지켜야 할 사항들을 알아보세요.",
        postState: "완료",
        sport: "클라이밍",
        viewCount: 850,
        likeCount: 100,
        commentCount: 25,
        tag: ["클라이밍", "안전", "초보자"],
        image: "images/climbing_safety.jpg"
    },
    {
        createdDate: "2024-09-07T10:25:45.000Z",
        title: "테니스 경기 예측, 나달 vs 조코비치",
        content: "테니스 팬들은 언제나 최고의 경기를 기다리고 있습니다. 나달과 조코비치의 경기 예측과 그들이 경기에서 펼칠 전술을 분석합니다.",
        postState: "예측",
        sport: "테니스",
        viewCount: 2200,
        likeCount: 190,
        commentCount: 85,
        tag: ["테니스", "경기예측", "나달", "조코비치"],
        image: "images/tennis_rivalry.jpg"
    },
    {
        createdDate: "2024-09-06T03:00:20.000Z",
        title: "헬스장에서 효과적인 운동 루틴 만들기",
        content: "헬스장에서는 다양한 운동 기구와 트레이닝 옵션이 있습니다. 각 운동의 효과적인 루틴을 만들기 위한 팁을 제공합니다.",
        postState: "완료",
        sport: "헬스",
        viewCount: 2000,
        likeCount: 170,
        commentCount: 60,
        tag: ["헬스", "운동루틴", "트레이닝"],
        image: "images/gym_workout_routine.jpg"
    }
];
